/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionaryApp;

import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import dictionary.dic.Dictionary;
import dictionary.dic.DictionaryManagement;
import dictionary.dic.Word;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;

/**
 *
 * @author Tram Tram
 */
public class DictionaryJFrame extends javax.swing.JFrame {
    DefaultListModel model = new DefaultListModel();
    Dictionary dictionary = new Dictionary();
    DictionaryManagement dictionaryManagement = new DictionaryManagement();

    /**
     * Creates new form DictionaryJFrame
     * @throws java.io.FileNotFoundException
     */
    public DictionaryJFrame() throws FileNotFoundException {
        initComponents();
        ExportListWord();
    }
    
    /*public Dictionary insertFromFile(Dictionary dictionary) throws FileNotFoundException {
        Scanner sc = new Scanner(new File("C:\\Users\\tramt\\IdeaProjects\\Project20_21\\src\\dictionary.txt")).useDelimiter("\t");
        while (sc.hasNext()) {
            String eng = sc.next();
            String vn = sc.nextLine();
            vn = vn.substring(1);
            vn = vn.toLowerCase();
            eng = eng.toLowerCase();
            dictionary.listOfWords.add(new Word(eng, vn));
        }
        return dictionary;
    }*/
    
    /**
     *
     * @throws FileNotFoundException
     */
    public void ExportListWord() throws FileNotFoundException {
        dictionaryManagement.insertFromFileForFrame(dictionary);
        for(int i = 0; i < dictionary.listOfWords.size(); i++) {
            model.addElement(dictionary.listOfWords.get(i).getWord_target());
        }
        listWord.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        search = new javax.swing.JButton();
        fix = new javax.swing.JButton();
        add = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listWord = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        explainArea = new javax.swing.JTextArea();
        speak = new javax.swing.JButton();
        googleTranslate = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dictionary");

        title.setBackground(new java.awt.Color(0, 51, 51));
        title.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cat.png"))); // NOI18N
        title.setText("         ENG - VIE DICTIONARY");
        title.setOpaque(true);

        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png"))); // NOI18N
        search.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                searchMouseMoved(evt);
            }
        });
        search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchMouseExited(evt);
            }
        });
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        fix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fix.png"))); // NOI18N
        fix.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                fixMouseMoved(evt);
            }
        });
        fix.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                fixMouseExited(evt);
            }
        });
        fix.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixActionPerformed(evt);
            }
        });

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png"))); // NOI18N
        add.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                addMouseMoved(evt);
            }
        });
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addMouseExited(evt);
            }
        });
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png"))); // NOI18N
        delete.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                deleteMouseMoved(evt);
            }
        });
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteMouseExited(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        searchField.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchField.setText("Insert word here");
        searchField.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                searchFieldCaretUpdate(evt);
            }
        });
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchFieldMouseClicked(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        listWord.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        listWord.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listWordValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listWord);

        explainArea.setColumns(20);
        explainArea.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        explainArea.setRows(5);
        jScrollPane2.setViewportView(explainArea);

        speak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/speak.png"))); // NOI18N
        speak.setToolTipText("");
        speak.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                speakMouseMoved(evt);
            }
        });
        speak.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                speakMouseExited(evt);
            }
        });
        speak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                speakActionPerformed(evt);
            }
        });

        googleTranslate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ggTranslate.png"))); // NOI18N
        googleTranslate.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                googleTranslateMouseMoved(evt);
            }
        });
        googleTranslate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                googleTranslateMouseExited(evt);
            }
        });
        googleTranslate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleTranslateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, 1177, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fix, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(googleTranslate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(speak, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(search, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8)))
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(fix, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(googleTranslate, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(speak, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        String findWord=searchField.getText();
        explainArea.setText(dictionaryManagement.dictionaryFrameLookUp(dictionary, findWord));
    }//GEN-LAST:event_searchActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        Delete delete = new Delete();
        delete.setLocationRelativeTo(null);
        delete.setVisible(true);
    }//GEN-LAST:event_deleteActionPerformed

    private void fixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixActionPerformed
        // TODO add your handling code here:
        Fix fix = new Fix();
        fix.setLocationRelativeTo(null);
        fix.setVisible(true); 
    }//GEN-LAST:event_fixActionPerformed

    private void fixMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixMouseMoved
        // TODO add your handling code here:
        fix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fix1.png")));
        fix.setToolTipText("Fix Word");
    }//GEN-LAST:event_fixMouseMoved

    private void fixMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fixMouseExited
        // TODO add your handling code here:
        fix.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/fix.png")));
    }//GEN-LAST:event_fixMouseExited

    private void deleteMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseMoved
        // TODO add your handling code here:
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete1.png")));
        delete.setToolTipText("Delete Word");
    }//GEN-LAST:event_deleteMouseMoved

    private void deleteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseExited
        // TODO add your handling code here:
        delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/delete.png")));
    }//GEN-LAST:event_deleteMouseExited

    private void searchMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseMoved
        // TODO add your handling code here:
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search1.png")));
        search.setToolTipText("Search Word");
    }//GEN-LAST:event_searchMouseMoved

    private void searchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchMouseExited
        // TODO add your handling code here:
        search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search.png")));
    }//GEN-LAST:event_searchMouseExited

    private void addMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseMoved
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add1.png")));
        add.setToolTipText("Add Word");
    }//GEN-LAST:event_addMouseMoved

    private void addMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseExited
        // TODO add your handling code here:
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/add.png")));
    }//GEN-LAST:event_addMouseExited

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
        /*model = new DefaultListModel();
        model.clear();
       
        for (Word element : dictionary.listOfWords) {
            model.addElement(element.getWord_target());
        }
            
        listWord.setModel(model);*/
    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_searchFieldCaretUpdate
        // TODO add your handling code here:
        String text = searchField.getText();
        model = new DefaultListModel();
        model.clear();
       
        for (Word element : dictionary.listOfWords) {
            if (element.getWord_target().startsWith(text)) {
                model.addElement(element.getWord_target());
            }
        }  
        listWord.setModel(model);
    }//GEN-LAST:event_searchFieldCaretUpdate

    private void listWordValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listWordValueChanged
        // TODO add your handling code here:
        explainArea.setText(dictionaryManagement.dictionaryFrameLookUp(dictionary, listWord.getSelectedValue()));
        //word.setWord_target(listWord.getSelectedValue());
    }//GEN-LAST:event_listWordValueChanged

    private void searchFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseClicked
        // TODO add your handling code here:
        searchField.setText(null);
        model = new DefaultListModel();
        model.clear();
       
        for (Word element : dictionary.listOfWords) {
            model.addElement(element.getWord_target());
        }
            
        listWord.setModel(model);
    }//GEN-LAST:event_searchFieldMouseClicked

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
        Add add = new Add();
        add.setLocationRelativeTo(null);
        add.setVisible(true);  
    }//GEN-LAST:event_addActionPerformed

    private void speakMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speakMouseMoved
        // TODO add your handling code here:
        speak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/speak1.png")));
        speak.setToolTipText("Speak");
    }//GEN-LAST:event_speakMouseMoved

    private void speakMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_speakMouseExited
        // TODO add your handling code here:
        speak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/speak.png")));
    }//GEN-LAST:event_speakMouseExited

    private void speakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_speakActionPerformed
        // TODO add your handling code here:
        VoiceManager vm;
        Voice v;
        vm = VoiceManager.getInstance();
        System.setProperty("mbrola.base", "mbrola");
        v = vm.getVoice("mbrola_us1");
        v.allocate();
        
        if(listWord.getSelectedValue()==null) {
            v.speak(searchField.getText());
        } else {
            v.speak(listWord.getSelectedValue());
        }
    }//GEN-LAST:event_speakActionPerformed

    private void googleTranslateMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_googleTranslateMouseMoved
        // TODO add your handling code here:
        googleTranslate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ggTranslate1.png")));
        googleTranslate.setToolTipText("Google Translate Online");
    }//GEN-LAST:event_googleTranslateMouseMoved

    private void googleTranslateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_googleTranslateMouseExited
        // TODO add your handling code here:
        googleTranslate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ggTranslate.png")));
    }//GEN-LAST:event_googleTranslateMouseExited

    private void googleTranslateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleTranslateActionPerformed
        // TODO add your handling code here:
        GoogleTranslate ggTrans = new GoogleTranslate();
        ggTrans.setLocationRelativeTo(null);
        ggTrans.setVisible(true);
    }//GEN-LAST:event_googleTranslateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DictionaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DictionaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DictionaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DictionaryJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    DictionaryJFrame df = new DictionaryJFrame();
                    df.setLocationRelativeTo(null);
                    df.setVisible(true);
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(DictionaryJFrame.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    private javax.swing.JTextArea explainArea;
    private javax.swing.JButton fix;
    private javax.swing.JButton googleTranslate;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listWord;
    private javax.swing.JButton search;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton speak;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
