/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionaryApp;

import dictionary.dic.Dictionary;
import dictionary.dic.DictionaryManagement;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Tram Tram
 */
public class Fix extends javax.swing.JFrame {
    Dictionary dictionary=new Dictionary();
    DictionaryManagement dictionaryManagement=new DictionaryManagement();

    /**
     * Creates new form Fix
     */
    public Fix() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        wordField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        targetField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        explainField = new javax.swing.JTextField();
        fixButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        success = new javax.swing.JLabel();
        fail = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Fix Word");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Word to fix");

        wordField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Fix word");

        targetField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Fix meaning");

        explainField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        explainField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                explainFieldActionPerformed(evt);
            }
        });

        fixButton.setText("Fix");
        fixButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fixButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        success.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        success.setForeground(new java.awt.Color(0, 204, 0));

        fail.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fail.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(fixButton)
                        .addGap(92, 92, 92)
                        .addComponent(cancelButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(success, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fail, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(wordField)
                                    .addComponent(targetField)
                                    .addComponent(explainField, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE))))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wordField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(targetField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(explainField, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(success, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(fail, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fixButton)
                    .addComponent(cancelButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void explainFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_explainFieldActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_explainFieldActionPerformed

    private void fixButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fixButtonActionPerformed
        // TODO add your handling code here:
        String word = wordField.getText();
        String target = targetField.getText();
        String explain = explainField.getText();
        
        word = word.toLowerCase();
        target = target.toLowerCase();
        explain = explain.toLowerCase();
        
        try {
            dictionaryManagement.insertFromFile(dictionary);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Fix.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if (word.isEmpty() || (target.isEmpty() && explain.isEmpty())) {
            success.setText(null);
            fail.setText("You must fill the fields!");
        } else {
            int start = 0;
            int end = dictionary.listOfWords.size();
            int i = (start + end) / 2;
            
            while ((i != start && i != end)) {
                if (dictionary.listOfWords.get(i).getWord_target().compareTo(word) > 0) {
                    end = i;
                    i = (start + end) / 2;
                }
                else {
                    start = i;
                    i = (start + end) / 2;
                }
            }
            if (dictionary.listOfWords.get(i).getWord_target().compareTo(word) != 0) {
                success.setText(null);
                fail.setText("Word not existed!");
            } else {
                if (target.isEmpty() || explain.isEmpty()) {
                    if (target.isEmpty()) dictionary.listOfWords.get(i).setWord_explain(explain);
                    else dictionary.listOfWords.get(i).setWord_target(target);
                } else {
                    dictionary.listOfWords.get(i).setWord_explain(explain);
                    dictionary.listOfWords.get(i).setWord_target(target);
                }
                fail.setText(null);
                fail.setText(null);
                success.setText("Fix successfully!");
                
                try {
                    File file = new File("C:\\Users\\tramt\\OneDrive\\Documents\\NetBeansProjects\\Dictionary\\src\\tudien.txt");
                    FileWriter fw = new FileWriter(file);

                    for (int t = 0; t < dictionary.listOfWords.size(); t++) {
                        fw.write(dictionary.listOfWords.get(t).getWord_target() + '\t' + dictionary.listOfWords.get(t).getWord_explain() + '\n');
                    }
                    fw.close();
                } catch(Exception ex) {
                    ex.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_fixButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fix.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fix().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField explainField;
    private javax.swing.JLabel fail;
    private javax.swing.JButton fixButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel success;
    private javax.swing.JTextField targetField;
    private javax.swing.JTextField wordField;
    // End of variables declaration//GEN-END:variables
}
